
version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    enviroment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apisolid

